FROM golang:alpine AS builder
WORKDIR /build/
COPY go.mod go.sum ./
COPY main.go ./
COPY internal/ /build/internal/
COPY pkg/ /build/pkg/
RUN go mod tidy
RUN go build -o app

FROM alpine:latest  
WORKDIR /root/
COPY --from=builder /build/app ./
COPY web/ ./web/
COPY assets/ ./assets/
ENTRYPOINT ./app
EXPOSE 8080